
import { store } from "@/services/store/store";
import type { Metadata } from "next";
import { Provider } from "react-redux";
// import "./globals.css";

export const metadata: Metadata = {
  title: "N-G summarizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
        >
            {children}
      </body>
    </html>
        // </Provider>
  );
}
